# Change these first
owner: djidjya # Your GitHub organization or username, where this repository lives
repo: chatbos-uptime # The name of this repository

sites: # List of endpoints to track
  - name: Google
    url: https://www.google.com
assignees: # Users to assign downtime issues (optional)
  - niallrox

status-website:
  baseUrl: /repo # where "repo" is your repository name
  name: Your Status Website