# Change these first
owner: djidjya # Your GitHub organization or username, where this repository lives
repo: chatbos-uptime # The name of this repository

sites: # List of endpoints to track
  - name: Platform Prod
    url: https://chatbos.ai
  - name: Chat Prod
    url: https://chat.chatbos.ai/embed.iife.js
  - name: API Prod
    url: https://api.chatbos.ai/api/bots/59d23179-cbaf-4d07-8683-29d3965759cf
  - name: Platform Dev
    url: https://platform.dev.chatbos.ai
  - name: Chat Dev
    url: https://chat.dev.chatbos.ai/embed.iife.js
  - name: API Dev
    url: https://api.dev.chatbos.ai/api/bots/4b02cb6c-f315-4443-8a82-cf629584a316
assignees: # Users to assign downtime issues (optional)
  - niallrox

runner: "[self-hosted]"
status-website:
  baseUrl: /chatbos-uptime
  name: Status Website